// ====================================================================
// VINSTAY AI — SEED STANDARDIZED UNITS FROM EXCEL (Supabase PostgreSQL)
// Auto-generated by data normalization engine
// ====================================================================

import { PrismaClient, LayoutType, DoorLockType, UnitStatus } from '@prisma/client';

import { assertListingText } from '../src/modules/property/listing-text';
import { layoutTypeToKind } from '../src/modules/tenant/tenant.mappers';

const prisma = new PrismaClient();

const BUILDINGS: Record<string, { zone: string; floors: number; lat: number; lng: number }> = {
  "S1.01": {
    "zone": "The Sapphire 1",
    "floors": 27,
    "lat": 20.999512,
    "lng": 105.945821
  },
  "S1.02": {
    "zone": "The Sapphire 1",
    "floors": 28,
    "lat": 20.998412,
    "lng": 105.945281
  },
  "S1.03": {
    "zone": "The Sapphire 1",
    "floors": 28,
    "lat": 20.997812,
    "lng": 105.944981
  },
  "S1.05": {
    "zone": "The Sapphire 1",
    "floors": 27,
    "lat": 20.999152,
    "lng": 105.946123
  },
  "S1.08": {
    "zone": "The Sapphire 1",
    "floors": 28,
    "lat": 20.998901,
    "lng": 105.946892
  },
  "S1.10": {
    "zone": "The Sapphire 1",
    "floors": 28,
    "lat": 20.997541,
    "lng": 105.947211
  },
  "S1.12": {
    "zone": "The Sapphire 1",
    "floors": 27,
    "lat": 20.996891,
    "lng": 105.948123
  },
  "S2.01": {
    "zone": "The Sapphire 2",
    "floors": 30,
    "lat": 20.996541,
    "lng": 105.942189
  },
  "S2.05": {
    "zone": "The Sapphire 2",
    "floors": 30,
    "lat": 20.995812,
    "lng": 105.943121
  },
  "S2.07": {
    "zone": "The Sapphire 2",
    "floors": 30,
    "lat": 20.994912,
    "lng": 105.944123
  },
  "S2.12": {
    "zone": "The Sapphire 2",
    "floors": 26,
    "lat": 20.994123,
    "lng": 105.942891
  },
  "S2.18": {
    "zone": "The Sapphire 2",
    "floors": 26,
    "lat": 20.993512,
    "lng": 105.941821
  },
  "ZR1": {
    "zone": "The Zenpark",
    "floors": 31,
    "lat": 20.992141,
    "lng": 105.939812
  },
  "ZR2": {
    "zone": "The Zenpark",
    "floors": 31,
    "lat": 20.991823,
    "lng": 105.939211
  },
  "R1.02": {
    "zone": "The Zenpark",
    "floors": 31,
    "lat": 20.991512,
    "lng": 105.938912
  },
  "P4": {
    "zone": "The Pavilion",
    "floors": 30,
    "lat": 20.993121,
    "lng": 105.937812
  },
  "BE3": {
    "zone": "The Beverly",
    "floors": 30,
    "lat": 20.990812,
    "lng": 105.936512
  },
  "BE-STU": {
    "zone": "The Beverly",
    "floors": 30,
    "lat": 20.990812,
    "lng": 105.936512
  },
  "M2": {
    "zone": "Masteri Waterfront",
    "floors": 30,
    "lat": 20.995123,
    "lng": 105.948912
  },
  "M3": {
    "zone": "Masteri Waterfront",
    "floors": 30,
    "lat": 20.994812,
    "lng": 105.949211
  },
  "H1": {
    "zone": "Masteri Waterfront",
    "floors": 26,
    "lat": 20.996123,
    "lng": 105.947812
  }
};

const UNITS_DATA: any[] = [
  {
    "source_row": 1,
    "unitCode": "VHOP-S1.02-0502",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 5,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 8000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_001",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 2Ngủ2Wc Full Đồ nội thất giá chỉ 8tr5/tháng LH em 0979841233"
  },
  {
    "source_row": 2,
    "unitCode": "VHOP-S1.02-0803",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 8,
    "layoutType": "STUDIO",
    "carpetAreaM2": 32.5,
    "baseRentPrice": 6000000,
    "managementFee": 308750,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 400000,
    "marketAvgPrice": 5500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_002",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "STUDIO Giá 6tr4 full đồ hỗ trợ xem nhà / vào luôn 0986400190"
  },
  {
    "source_row": 3,
    "unitCode": "VHOP-S1.03-1104",
    "buildingCode": "S1.03",
    "zoneName": "The Sapphire 1",
    "floorNumber": 11,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_003",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 1N+ full đồ toà S1.03 vào ở luôn giá 7tr LH xem nhà 0342546283"
  },
  {
    "source_row": 4,
    "unitCode": "VHOP-S1.02-1405",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 14,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 6000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_004",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg"
    ],
    "description": "1 ngủ nguyên bản có rèm,Nl giá 6 triệu rẻ nhất zr…"
  },
  {
    "source_row": 5,
    "unitCode": "VHOP-M2-1706",
    "buildingCode": "M2",
    "zoneName": "Masteri Waterfront",
    "floorNumber": 17,
    "layoutType": "THREE_BED",
    "carpetAreaM2": 78.0,
    "baseRentPrice": 15000000,
    "managementFee": 741000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 13500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_005",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg"
    ],
    "description": "cho thuê M2, 3N nội thất đẹp, 15tr KBP…"
  },
  {
    "source_row": 6,
    "unitCode": "VHOP-S1.02-2007",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 20,
    "layoutType": "STUDIO",
    "carpetAreaM2": 32.5,
    "baseRentPrice": 6000000,
    "managementFee": 308750,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 400000,
    "marketAvgPrice": 5500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_006",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "căn Studio, full đồ 6tr/tháng, VinHomes Ocean Park 3 Khu thời đại Phòng đầy đủ, bếp, tủ lạnh, máy giặt, điều hoà, nóng lạnh Đóng 2 cọc 1 hợp đồng 1 năm Điện 3.8k số"
  },
  {
    "source_row": 7,
    "unitCode": "VHOP-ZR2-2308",
    "buildingCode": "ZR2",
    "zoneName": "The Zenpark",
    "floorNumber": 23,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 11000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_007",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "căn hộ ZR2, full đồ, 2 ban công thoáng, sáng, view sông San Hô, gần trường học, nhà để xe. Free gym, game Giá : 11tr/tháng không bao phí, hợp đồng 1 năm, đ…"
  },
  {
    "source_row": 8,
    "unitCode": "VHOP-S1.05-2609",
    "buildingCode": "S1.05",
    "zoneName": "The Sapphire 1",
    "floorNumber": 26,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 8000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_008",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "căn 2n2vs Toà s1.05 Full đồ - Giá 8tr5 bao phí LH 0332983122"
  },
  {
    "source_row": 11,
    "unitCode": "VHOP-S1.02-1012",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 10,
    "layoutType": "THREE_BED",
    "carpetAreaM2": 78.0,
    "baseRentPrice": 12000000,
    "managementFee": 741000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 13500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_011",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 3Ngủ2Wc Full đồ đẹp , tầm view thoáng 12tr/tháng …"
  },
  {
    "source_row": 12,
    "unitCode": "VHOP-BE3-1301",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 13,
    "layoutType": "STUDIO",
    "carpetAreaM2": 32.5,
    "baseRentPrice": 5000000,
    "managementFee": 308750,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 400000,
    "marketAvgPrice": 5500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_012",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg"
    ],
    "description": "Cho thuê stu beverly giá 5tr, 1N 6tr có rèm nóng lạnh lh: 0963926918"
  },
  {
    "source_row": 13,
    "unitCode": "VHOP-S2.18-1602",
    "buildingCode": "S2.18",
    "zoneName": "The Sapphire 2",
    "floorNumber": 16,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 10000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_013",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "căn 2N2VS toà S2.18 Giá thuê : 10.000.000/tháng Full đồ vào ở luôn"
  },
  {
    "source_row": 14,
    "unitCode": "VHOP-H1-1903",
    "buildingCode": "H1",
    "zoneName": "Masteri Waterfront",
    "floorNumber": 19,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 8000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_014",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Độc quyền H1 – 1N+ nguyên bản | 8tr KBP Một căn nhà thật dễ chịu với view công viên Botanic, tầng trung nên cực kỳ thoáng và mát Chưa từng cho thuê, nhà còn rất mới Vào ở luôn – sẵn pass xem nhà"
  },
  {
    "source_row": 15,
    "unitCode": "VHOP-S1.02-2204",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 22,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 8000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_015",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Căn 2pn2wc tòa S1. 05 full đồ GIÁ 8tr5 BAO PHÍ. Lh Zalo 0382142394"
  },
  {
    "source_row": 16,
    "unitCode": "VHOP-S2.05-2505",
    "buildingCode": "S2.05",
    "zoneName": "The Sapphire 2",
    "floorNumber": 25,
    "layoutType": "STUDIO",
    "carpetAreaM2": 32.5,
    "baseRentPrice": 6000000,
    "managementFee": 308750,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 400000,
    "marketAvgPrice": 5500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_016",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "căn Stu toà s2.05 Full đồ - Giá 6tr LH 0332983122"
  },
  {
    "source_row": 18,
    "unitCode": "VHOP-S1.02-0607",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 6,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 5000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_018",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "Căn 1pn+ tòa S1. 08 nguyên bản GIÁ 5tr vào ở luôn. Lh Zalo 0382142394"
  },
  {
    "source_row": 19,
    "unitCode": "VHOP-S1.02-0908",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 9,
    "layoutType": "TWO_BED_ONE_BATH",
    "carpetAreaM2": 55.0,
    "baseRentPrice": 8000000,
    "managementFee": 522500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 8500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_019",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "2N1 8tr bao phí full đồ hỗ trợ xem nhà / vào luôn 0986400190"
  },
  {
    "source_row": 21,
    "unitCode": "VHOP-S1.02-1510",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 15,
    "layoutType": "TWO_BED_ONE_BATH",
    "carpetAreaM2": 55.0,
    "baseRentPrice": 8000000,
    "managementFee": 522500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 8500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_021",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 2n1 #8tr full đồ S2 Lh 0343372251"
  },
  {
    "source_row": 22,
    "unitCode": "VHOP-S1.02-1811",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 18,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_022",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Căn 1pn+ tòa S2. 12 full đồ GIÁ 7tr5 vào ở luôn Lh Zalo 0381142394"
  },
  {
    "source_row": 24,
    "unitCode": "VHOP-BE3-2401",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 24,
    "layoutType": "THREE_BED",
    "carpetAreaM2": 78.0,
    "baseRentPrice": 22000000,
    "managementFee": 741000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 13500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_024",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "căn 3N2 Vs: Beverly Be3 22.000.000/tháng tại OceanPank …"
  },
  {
    "source_row": 25,
    "unitCode": "VHOP-BE3-0202",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 2,
    "layoutType": "THREE_BED",
    "carpetAreaM2": 78.0,
    "baseRentPrice": 22000000,
    "managementFee": 741000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 13500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_025",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "SIÊU PHẨM 3PN2WC BE3 CẦN TÌM KHÁCH Full nội thất đẹp: 22tr(kbp) Hợp đồng 1 năm thanh toán 3cọc1 Vào được luôn Liên hệ: 0989821689"
  },
  {
    "source_row": 27,
    "unitCode": "VHOP-BE3-0804",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 8,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 6000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_027",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "căn 1N Be Nguyên bản có lắp rèm nóng lạnh Tầng trung view thoáng Diện tích 48m2 , 2 ban công Giá 6tr/ tháng"
  },
  {
    "source_row": 28,
    "unitCode": "VHOP-S1.12-1105",
    "buildingCode": "S1.12",
    "zoneName": "The Sapphire 1",
    "floorNumber": 11,
    "layoutType": "THREE_BED",
    "carpetAreaM2": 78.0,
    "baseRentPrice": 12500000,
    "managementFee": 741000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 13500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_028",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 3pn2vs toà S1.12,NT Full đồ,Trống vào luôn Giá 12.5tr/thánG LH:0358735939"
  },
  {
    "source_row": 29,
    "unitCode": "VHOP-S1.02-1406",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 14,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_029",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "1 ngủ + full đồ viu uni giá tốt chỉ 7 triệu…"
  },
  {
    "source_row": 30,
    "unitCode": "VHOP-R1.02-1707",
    "buildingCode": "R1.02",
    "zoneName": "The Zenpark",
    "floorNumber": 17,
    "layoutType": "STUDIO",
    "carpetAreaM2": 32.5,
    "baseRentPrice": 6400000,
    "managementFee": 308750,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 400000,
    "marketAvgPrice": 5500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_030",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "Cho thu.ê căn studio toà Ruby chỉ 6.4tr/ tháng ZL : 0961439901"
  },
  {
    "source_row": 31,
    "unitCode": "VHOP-S1.02-2008",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 20,
    "layoutType": "TWO_BED_ONE_BATH",
    "carpetAreaM2": 55.0,
    "baseRentPrice": 8000000,
    "managementFee": 522500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 8500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_031",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Căn 2pn1wc tòa S2. 07 full đồ GIÁ 8tr vào ở luôn. Lh Zalo 0382142394"
  },
  {
    "source_row": 32,
    "unitCode": "VHOP-S1.02-2309",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 23,
    "layoutType": "STUDIO",
    "carpetAreaM2": 32.5,
    "baseRentPrice": 7500000,
    "managementFee": 308750,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 400000,
    "marketAvgPrice": 5500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_032",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "căn Studio full nội thất mới tinh chưa qua sử dụng cho thuê giá 7,5tr Lh: 0586851998"
  },
  {
    "source_row": 33,
    "unitCode": "VHOP-S1.02-2610",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 26,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_033",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "1 ngủ + full đồ viu uni giá 7 triệu…"
  },
  {
    "source_row": 34,
    "unitCode": "VHOP-S1.02-0411",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 4,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7500000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_034",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "Cho thu.ê 1N+ toà S chỉ 7.5tr/ tháng bao phí - ZL : 0961439901 #nhavinhomes #hoangtu #masterisehomes #nhanow"
  },
  {
    "source_row": 35,
    "unitCode": "VHOP-S2.05-0712",
    "buildingCode": "S2.05",
    "zoneName": "The Sapphire 2",
    "floorNumber": 7,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_035",
    "images": [
      "anh_1.jpg"
    ],
    "description": "cho thuê 1PN+ full đồ S205 Vinhomes Ocean Park Giá 7tr/th LH xem nhà: 0961057036"
  },
  {
    "source_row": 36,
    "unitCode": "VHOP-S1.02-1001",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 10,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 5000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_036",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "căn 1pn+ nguyên bản giá 5tr LH : 0332983122"
  },
  {
    "source_row": 37,
    "unitCode": "VHOP-R1.02-1302",
    "buildingCode": "R1.02",
    "zoneName": "The Zenpark",
    "floorNumber": 13,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 9500000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_037",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "căn : R1 Loại căn : 1N+ Nội thất : full đồ Giá : 9,5tr bp"
  },
  {
    "source_row": 38,
    "unitCode": "VHOP-ZR1-1603",
    "buildingCode": "ZR1",
    "zoneName": "The Zenpark",
    "floorNumber": 16,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 6000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_038",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Căn 1pn+ tòa Zr1 nguyên bản GIÁ 6tr5 (có tl) vào ở luôn. Lh Zalo 0382142394"
  },
  {
    "source_row": 39,
    "unitCode": "VHOP-P4-1904",
    "buildingCode": "P4",
    "zoneName": "The Pavilion",
    "floorNumber": 19,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 8500000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_039",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 1n+ toà P4 (48m2) giá 8,5tr Lhe e xem nhà: 0969.219.657"
  },
  {
    "source_row": 40,
    "unitCode": "VHOP-S1.01-2205",
    "buildingCode": "S1.01",
    "zoneName": "The Sapphire 1",
    "floorNumber": 22,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 8000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_040",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "Cho thuê 2N2Vs S101 full đồ đẹp 8tr5 0344270683"
  },
  {
    "source_row": 41,
    "unitCode": "VHOP-M2-2506",
    "buildingCode": "M2",
    "zoneName": "Masteri Waterfront",
    "floorNumber": 25,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 8000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_041",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "Cho thuê #1N+ rộng 48m2 full nội thất mới tinh như ảnh giá 8tr5 liên hệ: 0349791883"
  },
  {
    "source_row": 43,
    "unitCode": "VHOP-S1.02-0608",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 6,
    "layoutType": "THREE_BED",
    "carpetAreaM2": 78.0,
    "baseRentPrice": 22000000,
    "managementFee": 741000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 13500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_043",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Căn phân khu cao cấp #3N2VS toà M 22 tr/tháng LH em 0981912854"
  },
  {
    "source_row": 44,
    "unitCode": "VHOP-S2.18-0909",
    "buildingCode": "S2.18",
    "zoneName": "The Sapphire 2",
    "floorNumber": 9,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_044",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "căn hộ 1pn+ Toà S2.18 Full đồ - giá 7tr kbp LH 0332983122"
  },
  {
    "source_row": 45,
    "unitCode": "VHOP-M3-1210",
    "buildingCode": "M3",
    "zoneName": "Masteri Waterfront",
    "floorNumber": 12,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 14000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_045",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 2N2 tại Masteri M3 Full đồ 14tr…"
  },
  {
    "source_row": 46,
    "unitCode": "VHOP-R1.02-1511",
    "buildingCode": "R1.02",
    "zoneName": "The Zenpark",
    "floorNumber": 15,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 8000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_046",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "căn 1N toà Ruby full nội thất giá 8tr bao phí Lhe: 0384.829.903"
  },
  {
    "source_row": 47,
    "unitCode": "VHOP-S1.02-1812",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 18,
    "layoutType": "THREE_BED",
    "carpetAreaM2": 78.0,
    "baseRentPrice": 19000000,
    "managementFee": 741000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 13500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_047",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "CĂN 3N2W VIEW HỒ – PHÂN KHU MASTERI Full nội thất, vào ở ngay View hồ thoáng đẹp Giá thuê: 19 triệu/tháng LH em: 0816692604"
  },
  {
    "source_row": 48,
    "unitCode": "VHOP-BE3-2101",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 21,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 8700000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_048",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 2N2 beverly Full đồ 8,7tr …"
  },
  {
    "source_row": 49,
    "unitCode": "VHOP-BE3-2402",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 24,
    "layoutType": "STUDIO",
    "carpetAreaM2": 32.5,
    "baseRentPrice": 6500000,
    "managementFee": 308750,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 400000,
    "marketAvgPrice": 5500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_049",
    "images": [
      "anh_1.jpg"
    ],
    "description": "Cho thuê Studio Beverly full đồ xinh (giá 6,5tr cbp)…"
  },
  {
    "source_row": 51,
    "unitCode": "VHOP-S1.12-0504",
    "buildingCode": "S1.12",
    "zoneName": "The Sapphire 1",
    "floorNumber": 5,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 9000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_051",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 2n2w S1.12 Nội thất: Full đồ đẹp, hướng ĐB, view hồ, biệt thự Giá: 9tr / tháng Vào ở được luôn Liên hệ: 0985492193"
  },
  {
    "source_row": 52,
    "unitCode": "VHOP-BE3-0805",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 8,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 7000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_052",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg"
    ],
    "description": "Cho Thuê 2N2WC Căn Góc Phân Khu The Beverly 𝐍𝐨̣̂𝐢 𝐓𝐡𝐚̂́𝐭 : full đồ cơ bản tủ bếp (rèm,nl,đh) 𝐆𝐢á 𝗧𝗵𝘂𝗲̂ : 7tr5 kbp Hình thức đóng: Hđ 1 năm đóng 3c1 Thời gian Xem nhà : báo trước"
  },
  {
    "source_row": 53,
    "unitCode": "VHOP-BE3-1106",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 11,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 8000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_053",
    "images": [
      "anh_1.jpg"
    ],
    "description": "Cho thuê 1N Beverly full đồ xịn xò (giá 8tr cbp)…"
  },
  {
    "source_row": 55,
    "unitCode": "VHOP-S1.03-1708",
    "buildingCode": "S1.03",
    "zoneName": "The Sapphire 1",
    "floorNumber": 17,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_055",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "1N+ S1.03 Full đồ đẹp giá 7tr8 bao phí Vào ở được ngay sẵn pass xem nhà LH 0355076297 ( Zalo )"
  },
  {
    "source_row": 56,
    "unitCode": "VHOP-BE3-2009",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 20,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 9000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_056",
    "images": [
      "anh_1.jpg"
    ],
    "description": "Cho thuê 2N2VS Beverly full đồ đẹp (giá 9tr cbp)…"
  },
  {
    "source_row": 58,
    "unitCode": "VHOP-S1.08-2611",
    "buildingCode": "S1.08",
    "zoneName": "The Sapphire 1",
    "floorNumber": 26,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 5500000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": true,
    "canFolder": "can_058",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "căn 1N+ nguyên bản tòa S1.08 Cho thuê 5.500.000…"
  },
  {
    "source_row": 59,
    "unitCode": "VHOP-S1.01-0412",
    "buildingCode": "S1.01",
    "zoneName": "The Sapphire 1",
    "floorNumber": 4,
    "layoutType": "TWO_BED_ONE_BATH",
    "carpetAreaM2": 55.0,
    "baseRentPrice": 10000000,
    "managementFee": 522500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 8500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_059",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Cho thuê 2N full đồ đẹp Toà S1.01 Giá 10Tr (bao phí) …"
  },
  {
    "source_row": 60,
    "unitCode": "VHOP-S1.02-0701",
    "buildingCode": "S1.02",
    "zoneName": "The Sapphire 1",
    "floorNumber": 7,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 8500000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_060",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Siêu phẩm 1N Luxury nội thất nhập ngoại 100% Giá chỉ 8.5 triệu / tháng …"
  },
  {
    "source_row": 61,
    "unitCode": "VHOP-R1.02-1002",
    "buildingCode": "R1.02",
    "zoneName": "The Zenpark",
    "floorNumber": 10,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 8000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_061",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "1N Ruby 8 triệu bao phí LH 0355076297 ( Zalo )"
  },
  {
    "source_row": 62,
    "unitCode": "VHOP-M2-1303",
    "buildingCode": "M2",
    "zoneName": "Masteri Waterfront",
    "floorNumber": 13,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 13000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_062",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "2n2+ view triệu đô toà M2 giá cho thuê chỉ 13tr full đủ đồ LH : 0326713508"
  },
  {
    "source_row": 63,
    "unitCode": "VHOP-BE3-1604",
    "buildingCode": "BE3",
    "zoneName": "The Beverly",
    "floorNumber": 16,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 11000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_063",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "BE | 2N2 GÓC 62,9M² – FULL ĐỒ 11TR KBP | Vào ở luôn HĐ 1 năm • 3 cọc 1 0392229006"
  },
  {
    "source_row": 64,
    "unitCode": "VHOP-P4-1905",
    "buildingCode": "P4",
    "zoneName": "The Pavilion",
    "floorNumber": 19,
    "layoutType": "TWO_BED_TWO_BATH",
    "carpetAreaM2": 64.0,
    "baseRentPrice": 11000000,
    "managementFee": 608000,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 9500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_064",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg",
      "anh_5.jpg"
    ],
    "description": "Toà: P4 Loại căn: 2n2 Nội thất: Full đồ Giá Thuê: 11.000.000 Bao phí: không (phí rẻ 600)…"
  },
  {
    "source_row": 65,
    "unitCode": "VHOP-S1.10-2206",
    "buildingCode": "S1.10",
    "zoneName": "The Sapphire 1",
    "floorNumber": 22,
    "layoutType": "ONE_BED_PLUS",
    "carpetAreaM2": 47.0,
    "baseRentPrice": 7000000,
    "managementFee": 446500,
    "parkingFeeEstimate": 150000,
    "utilityCostEstimate": 600000,
    "marketAvgPrice": 7500000,
    "doorLockType": "ELECTRONIC_PIN",
    "isVerified": true,
    "status": "AVAILABLE",
    "isHot": false,
    "canFolder": "can_065",
    "images": [
      "anh_1.jpg",
      "anh_2.jpg",
      "anh_3.jpg",
      "anh_4.jpg"
    ],
    "description": "Cho thuê 1N+ s110 full đồ Giá: 7 triệu bao phí Lh: 0972127419"
  }
];

/**
 * Title/description công khai (hồ sơ 18 SPEC-P01 §5): description gốc vi phạm B7 (SĐT/URL/tiền) ⇒ null,
 * title sinh từ trường cấu trúc. KHÔNG sửa tay dữ liệu JSON phía trên.
 */
function seedListingText(u: any): { title: string; description: string | null; rejected: boolean } {
  const title = `${layoutTypeToKind(u.layoutType as LayoutType)} ${u.carpetAreaM2}m² · ${u.zoneName}`;
  let description: string | null = typeof u.description === 'string' && u.description.trim() ? u.description.trim() : null;
  let rejected = false;
  if (description) {
    try {
      assertListingText('description', description);
    } catch {
      description = null;
      rejected = true;
    }
  }
  return { title, description, rejected };
}

async function main() {
  console.log('🚀 Pushing normalized units to Supabase PostgreSQL...');

  // 1. Ensure Roles exist
  const landlordRole = await prisma.role.upsert({
    where: { code: 'landlord' },
    update: {},
    create: { code: 'landlord', name: 'Chủ nhà', description: 'Chủ hộ ủy quyền ký gửi' },
  });

  // 2. Ensure Landlord Profile exists
  const landlordId = '33333333-3333-3333-3333-333333333333';
  await prisma.profile.upsert({
    where: { id: landlordId },
    update: { fullName: 'Nguyễn Văn Minh (Chủ nhà Ký gửi)' },
    create: {
      id: landlordId,
      roleId: landlordRole.id,
      fullName: 'Nguyễn Văn Minh (Chủ nhà Ký gửi)',
      email: 'landlord@vinstay.test',
      phoneHash: 'hash_0987654321',
      isPhoneVerified: true,
      isActive: true,
    },
  });

  // 3. Upsert Buildings
  console.log('👉 Upserting Buildings...');
  const buildingIdMap: Record<string, string> = {};
  for (const [code, spec] of Object.entries(BUILDINGS)) {
    const bldg = await prisma.building.upsert({
      where: { buildingCode: code },
      update: {
        zoneName: spec.zone,
        totalFloors: spec.floors,
        lobbyLatitude: spec.lat,
        lobbyLongitude: spec.lng,
      },
      create: {
        buildingCode: code,
        zoneName: spec.zone,
        totalFloors: spec.floors,
        lobbyLatitude: spec.lat,
        lobbyLongitude: spec.lng,
      },
    });
    buildingIdMap[code] = bldg.id;
  }

  // 4. Upsert Units & Media
  console.log(`👉 Upserting ${UNITS_DATA.length} Cleaned & Standardized Units...`);
  let inserted = 0;
  let descriptionsDropped = 0;
  for (const u of UNITS_DATA) {
    const buildingId = buildingIdMap[u.buildingCode];
    if (!buildingId) continue;

    const text = seedListingText(u);
    if (text.rejected) descriptionsDropped++;
    const unit = await prisma.unit.upsert({
      where: { unitCode: u.unitCode },
      update: {
        buildingId,
        landlordId,
        floorNumber: u.floorNumber,
        layoutType: u.layoutType as LayoutType,
        carpetAreaM2: u.carpetAreaM2,
        baseRentPrice: u.baseRentPrice,
        managementFee: u.managementFee,
        parkingFeeEstimate: u.parkingFeeEstimate,
        utilityCostEstimate: u.utilityCostEstimate,
        marketAvgPrice: u.marketAvgPrice,
        doorLockType: u.doorLockType as DoorLockType,
        isVerified: u.isVerified,
        status: UnitStatus.AVAILABLE,
        isHot: u.isHot,
        title: text.title,
        description: text.description,
      },
      create: {
        unitCode: u.unitCode,
        buildingId,
        landlordId,
        floorNumber: u.floorNumber,
        layoutType: u.layoutType as LayoutType,
        carpetAreaM2: u.carpetAreaM2,
        baseRentPrice: u.baseRentPrice,
        managementFee: u.managementFee,
        parkingFeeEstimate: u.parkingFeeEstimate,
        utilityCostEstimate: u.utilityCostEstimate,
        marketAvgPrice: u.marketAvgPrice,
        doorLockType: u.doorLockType as DoorLockType,
        isVerified: u.isVerified,
        status: UnitStatus.AVAILABLE,
        isHot: u.isHot,
        title: text.title,
        description: text.description,
      },
    });

    // Delete existing media for clean sync
    await prisma.unitMedia.deleteMany({ where: { unitId: unit.id } });

    // Insert media
    if (u.images && u.images.length > 0) {
      for (let i = 0; i < u.images.length; i++) {
        const imgName = u.images[i];
        const mediaUrl = `/units/${u.canFolder}/${imgName}`;
        await prisma.unitMedia.create({
          data: {
            unitId: unit.id,
            url: mediaUrl,
            category: i === 0 ? 'living_room' : i === 1 ? 'bedroom' : 'interior',
            order: i + 1,
          },
        });
      }
    }

    // Ensure Door Key exists
    await prisma.doorAccessKey.upsert({
      where: { unitId: unit.id },
      update: {},
      create: {
        unitId: unit.id,
        keyType: u.doorLockType as DoorLockType,
        vaultSecretRef: null, // chuỗi giữ chỗ cũ không phải PIN — chạy `npm run rekey:door-codes -- --apply` sau seed (hồ sơ 15)
      },
    });

    inserted++;
  }

  console.log(`✅ Successfully synced ${inserted} units and their media to Supabase PostgreSQL! (descriptions dropped by assertListingText: ${descriptionsDropped})`);
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
