import os
import shutil
import json
from normalize_dataset import clean_and_normalize, BUILDING_SPECS

src_img_dir = r"d:\AI VIN\P-010\tech data\data\imageluot6"
dest_img_dir = r"d:\AI VIN\P-010\apps\web\public\units"

def copy_images():
    os.makedirs(dest_img_dir, exist_ok=True)
    count = 0
    for item in os.listdir(src_img_dir):
        src_sub = os.path.join(src_img_dir, item)
        if os.path.isdir(src_sub):
            dest_sub = os.path.join(dest_img_dir, item)
            os.makedirs(dest_sub, exist_ok=True)
            for f in os.listdir(src_sub):
                if f.lower().endswith(('.jpg', '.jpeg', '.png')):
                    shutil.copy2(os.path.join(src_sub, f), os.path.join(dest_sub, f))
                    count += 1
    print(f"Copied {count} images to {dest_img_dir}")

def generate_prisma_seed_ts(units):
    bldg_json = json.dumps(BUILDING_SPECS, indent=2)
    units_json = json.dumps(units, indent=2, ensure_ascii=False)
    
    ts_content = """// ====================================================================
// VINSTAY AI — SEED STANDARDIZED UNITS FROM EXCEL (Supabase PostgreSQL)
// Auto-generated by data normalization engine
// ====================================================================

import { PrismaClient, LayoutType, DoorLockType, UnitStatus } from '@prisma/client';

const prisma = new PrismaClient();

const BUILDINGS: Record<string, { zone: string; floors: number; lat: number; lng: number }> = """ + bldg_json + """;

const UNITS_DATA: any[] = """ + units_json + """;

async function main() {
  console.log('🚀 Pushing normalized units to Supabase PostgreSQL...');

  // 1. Ensure Roles exist
  const landlordRole = await prisma.role.upsert({
    where: { code: 'landlord' },
    update: {},
    create: { code: 'landlord', name: 'Chủ nhà', description: 'Chủ hộ ủy quyền ký gửi' },
  });

  // 2. Ensure Landlord Profile exists
  const landlordId = '33333333-3333-3333-3333-333333333333';
  await prisma.profile.upsert({
    where: { id: landlordId },
    update: { fullName: 'Nguyễn Văn Minh (Chủ nhà Ký gửi)' },
    create: {
      id: landlordId,
      roleId: landlordRole.id,
      fullName: 'Nguyễn Văn Minh (Chủ nhà Ký gửi)',
      email: 'landlord@vinstay.test',
      phoneHash: 'hash_0987654321',
      isPhoneVerified: true,
      isActive: true,
    },
  });

  // 3. Upsert Buildings
  console.log('👉 Upserting Buildings...');
  const buildingIdMap: Record<string, string> = {};
  for (const [code, spec] of Object.entries(BUILDINGS)) {
    const bldg = await prisma.building.upsert({
      where: { buildingCode: code },
      update: {
        zoneName: spec.zone,
        totalFloors: spec.floors,
        lobbyLatitude: spec.lat,
        lobbyLongitude: spec.lng,
      },
      create: {
        buildingCode: code,
        zoneName: spec.zone,
        totalFloors: spec.floors,
        lobbyLatitude: spec.lat,
        lobbyLongitude: spec.lng,
      },
    });
    buildingIdMap[code] = bldg.id;
  }

  // 4. Upsert Units & Media
  console.log(`👉 Upserting ${UNITS_DATA.length} Cleaned & Standardized Units...`);
  let inserted = 0;
  for (const u of UNITS_DATA) {
    const buildingId = buildingIdMap[u.buildingCode];
    if (!buildingId) continue;

    const unit = await prisma.unit.upsert({
      where: { unitCode: u.unitCode },
      update: {
        buildingId,
        landlordId,
        floorNumber: u.floorNumber,
        layoutType: u.layoutType as LayoutType,
        carpetAreaM2: u.carpetAreaM2,
        baseRentPrice: u.baseRentPrice,
        managementFee: u.managementFee,
        parkingFeeEstimate: u.parkingFeeEstimate,
        utilityCostEstimate: u.utilityCostEstimate,
        marketAvgPrice: u.marketAvgPrice,
        doorLockType: u.doorLockType as DoorLockType,
        isVerified: u.isVerified,
        status: UnitStatus.AVAILABLE,
        isHot: u.isHot,
      },
      create: {
        unitCode: u.unitCode,
        buildingId,
        landlordId,
        floorNumber: u.floorNumber,
        layoutType: u.layoutType as LayoutType,
        carpetAreaM2: u.carpetAreaM2,
        baseRentPrice: u.baseRentPrice,
        managementFee: u.managementFee,
        parkingFeeEstimate: u.parkingFeeEstimate,
        utilityCostEstimate: u.utilityCostEstimate,
        marketAvgPrice: u.marketAvgPrice,
        doorLockType: u.doorLockType as DoorLockType,
        isVerified: u.isVerified,
        status: UnitStatus.AVAILABLE,
        isHot: u.isHot,
      },
    });

    // Delete existing media for clean sync
    await prisma.unitMedia.deleteMany({ where: { unitId: unit.id } });

    // Insert media
    if (u.images && u.images.length > 0) {
      for (let i = 0; i < u.images.length; i++) {
        const imgName = u.images[i];
        const mediaUrl = `/units/${u.canFolder}/${imgName}`;
        await prisma.unitMedia.create({
          data: {
            unitId: unit.id,
            url: mediaUrl,
            category: i === 0 ? 'living_room' : i === 1 ? 'bedroom' : 'interior',
            order: i + 1,
          },
        });
      }
    }

    // Ensure Door Key exists
    await prisma.doorAccessKey.upsert({
      where: { unitId: unit.id },
      update: {},
      create: {
        unitId: unit.id,
        keyType: u.doorLockType as DoorLockType,
        vaultSecretRef: `vault:aes256:door_pin:${u.unitCode}`,
      },
    });

    inserted++;
  }

  console.log(`✅ Successfully synced ${inserted} units and their media to Supabase PostgreSQL!`);
}

main()
  .catch((e) => {
    console.error('Error during seeding:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
"""
    with open(r"d:\AI VIN\P-010\backend\prisma\seed_excel_units.ts", "w", encoding="utf-8") as f:
        f.write(ts_content)
    print("Generated backend/prisma/seed_excel_units.ts successfully!")

if __name__ == "__main__":
    copy_images()
    units = clean_and_normalize()
    generate_prisma_seed_ts(units)
