from pathlib import Path
import ast
import os
import re
import sys


ROOT = Path.cwd()
PACK = ROOT / "ai-pack"
MAX_FILE_BYTES = 200 * 1024
SECRET_MARKER = "<!-- generated by tools/build_ai_inventories.py; locations only -->"
SECRET_VALUE = re.compile(
    r"(?i)\b(?:api[_-]?key|secret(?:[_-]?key)?|access[_-]?token|refresh[_-]?token|"
    r"password|passwd|credential|connection[_-]?string|database[_-]?url)\b"
    r"\s*(?:=|:)\s*(['\"])([^'\"\r\n]{8,})\1"
)
PLACEHOLDERS = ("test-key", "dummy", "changeme", "your_", "example", "placeholder")


def markdown_cell(value):
    return str(value).replace("|", "\\|").replace("\n", " ")


def read_safe(path, findings):
    if path.stat().st_size > MAX_FILE_BYTES:
        return None
    text = path.read_text(encoding="utf-8", errors="replace")
    relative = path.relative_to(ROOT).as_posix()
    for line_number, line in enumerate(text.splitlines(), 1):
        for match in SECRET_VALUE.finditer(line):
            value = match.group(2).lower()
            if not any(token in value for token in PLACEHOLDERS):
                findings.add(f"SECRET? tại {relative}:{line_number}")
    return text


def write_new(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8", newline="") as stream:
        stream.write(text)


def flush_findings(findings):
    if not findings:
        return
    target = PACK / "SECRET_FINDINGS.md"
    if target.exists():
        if target.stat().st_size > MAX_FILE_BYTES:
            raise SystemExit("SECRET_FINDINGS.md vượt 200 KB; giữ nguyên file hiện có")
        existing = target.read_text(encoding="utf-8")
        if not existing.startswith(SECRET_MARKER):
            raise SystemExit("SECRET_FINDINGS.md đã tồn tại và không thuộc script; giữ nguyên")
        present = set(existing.splitlines())
        added = sorted(findings - present)
        if added:
            with target.open("a", encoding="utf-8", newline="") as stream:
                stream.write("\n".join(added) + "\n")
    else:
        write_new(target, SECRET_MARKER + "\n\n" + "\n".join(sorted(findings)) + "\n")


def source_files(folder, suffixes=None):
    if not folder.exists():
        return []
    excluded = {"node_modules", ".git", ".ai-log", "tech data"}
    files = []
    for directory, subdirectories, filenames in os.walk(folder, followlinks=False):
        subdirectories[:] = [name for name in subdirectories if name not in excluded]
        for filename in filenames:
            path = Path(directory) / filename
            if suffixes is None or path.suffix.lower() in suffixes:
                files.append(path)
    return sorted(files)


def decorator_before(lines, index):
    result = []
    cursor = index - 1
    while cursor >= 0 and lines[cursor].strip().startswith("@"):
        result.insert(0, lines[cursor].strip())
        cursor -= 1
    return result


def parse_decorator(text):
    match = re.match(r"@([A-Za-z_]\w*)\s*(?:\((.*)\))?", text.strip())
    return (match.group(1), (match.group(2) or "").strip()) if match else ("", "")


def decorators_named(decorators, wanted):
    output = []
    for decorator in decorators:
        name, argument = parse_decorator(decorator)
        if name in wanted:
            output.append(f"@{name}({argument})" if argument else f"@{name}")
    return output


def controller_routes(path, text):
    lines = text.splitlines()
    class_matches = list(re.finditer(r"\bclass\s+(\w+Controller)\b", text))
    if not class_matches:
        class_matches = [None]
    results = []
    for class_match in class_matches:
        class_name = class_match.group(1) if class_match else path.stem
        class_line = text.count("\n", 0, class_match.start()) if class_match else 0
        class_decs = decorator_before(lines, class_line)
        controller = next((parse_decorator(item)[1] for item in class_decs if parse_decorator(item)[0] == "Controller"), "")
        controller = controller.strip("'\"`/")
        lower_bound = class_line + 1 if class_match else 0
        upper_bound = len(lines)
        if class_match:
            next_class = next((m for m in class_matches if m and m.start() > class_match.start()), None)
            if next_class:
                upper_bound = text.count("\n", 0, next_class.start())
        for line_number in range(lower_bound, upper_bound):
            route_match = re.match(r"\s*@(Get|Post|Put|Patch|Delete|Options|Head|All)\s*(?:\((.*?)\))?", lines[line_number])
            if not route_match:
                continue
            verb = route_match.group(1).upper()
            route = (route_match.group(2) or "").strip().strip("'\"`/")
            full_path = "/".join(part for part in (controller, route) if part)
            decorators = class_decs + decorator_before(lines, line_number) + [lines[line_number].strip()]
            guards = decorators_named(decorators, {"Public", "Roles", "UseGuards"})
            handler = "CHƯA RÕ"
            for following in lines[line_number + 1 : min(line_number + 12, upper_bound)]:
                method = re.match(r"\s*(?:(?:public|async|static|protected|private)\s+)*([A-Za-z_$][\w$]*)\s*\(", following)
                if method:
                    handler = method.group(1)
                    break
            guard_text = ", ".join(guards) if guards else "không thấy @Public/@Roles/@UseGuards gần route hoặc class"
            results.append(f"{class_name}: {verb} /{full_path} -> {handler}; {guard_text}")
    return results


def public_service_methods(text):
    names = []
    pattern = re.compile(r"^\s*(?:(public|private|protected)\s+)?(?:static\s+)?(?:async\s+)?([A-Za-z_$][\w$]*)\s*\(", re.M)
    for match in pattern.finditer(text):
        access, name = match.groups()
        if name != "constructor" and access not in {"private", "protected"}:
            names.append(name)
    return sorted(set(names))


def inventory_backend(findings):
    root = ROOT / "backend/src/modules"
    directories = [root] + sorted(path for path in root.rglob("*") if path.is_dir())
    rows = []
    for folder in directories:
        files = sorted(path for path in folder.iterdir() if path.is_file() and path.suffix == ".ts")
        if not files:
            continue
        module = folder.relative_to(root).as_posix() or "."
        controllers, services, dtos, tests = [], [], [], []
        all_ts = source_files(folder, {".ts"})
        for path in all_ts:
            text = read_safe(path, findings)
            if text is None:
                continue
            relative = path.relative_to(ROOT).as_posix()
            if "controller" in path.name.lower():
                controllers.extend(controller_routes(path, text))
            if "service" in path.name.lower():
                methods = public_service_methods(text)
                services.append(f"{path.name}: {', '.join(methods) if methods else 'CHƯA RÕ'}")
            if "dto" in path.name.lower() or "entity" in path.name.lower() or any(part.lower() in {"dto", "dtos", "entity", "entities"} for part in path.parts):
                dtos.append(path.name)
            if path.name.endswith(".spec.ts"):
                tests.append(relative)
        cells = [module, "<br>".join(controllers) or "Không thấy controller", "<br>".join(services) or "Không thấy service", ", ".join(sorted(set(dtos))) or "Không thấy DTO/entity", "<br>".join(tests) or "Không thấy spec"]
        rows.append("| " + " | ".join(markdown_cell(cell) for cell in cells) + " |")
    body = ["# Backend Inventory", "", "| Module | Controller: method/path và guard | Service: method public | DTO/entity (tên file) | Test liên quan |", "|---|---|---|---|---|"] + rows
    return "\n".join(body) + "\n"


def parse_prisma(text):
    models = {}
    enums = {}
    for match in re.finditer(r"\bmodel\s+(\w+)\s*\{([^}]*)\}", text, re.S):
        name, body = match.groups()
        fields = {}
        indexes = []
        table = name
        for line in body.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("//"):
                continue
            map_match = re.match(r'@@map\("([^\"]+)"\)', stripped)
            if map_match:
                table = map_match.group(1)
                continue
            index_match = re.match(r"@@(id|unique|index|fulltext)\s*\((.*)", stripped)
            if index_match:
                indexes.append(stripped)
                continue
            field = re.match(r"(\w+)\s+([\w]+(?:\[\])?\??)(.*)$", stripped)
            if not field:
                continue
            field_name, field_type, attributes = field.groups()
            mapped = re.search(r'@map\("([^\"]+)"\)', attributes)
            db_name = mapped.group(1) if mapped else field_name
            markers = [tag for tag in ("@id", "@unique", "@relation") if tag in attributes]
            relation = " relation" if "@relation" in attributes else ""
            fields[field_name] = {"type": field_type, "db_name": db_name, "relation": relation, "markers": markers}
        models[name] = {"table": table, "fields": fields, "indexes": indexes}
    model_names = set(models)
    for model in models.values():
        for info in model["fields"].values():
            base = info["type"].rstrip("?")
            base = base[:-2] if base.endswith("[]") else base
            if base in model_names:
                info["relation"] = " relation"
    for match in re.finditer(r"\benum\s+(\w+)\s*\{([^}]*)\}", text, re.S):
        enums[match.group(1)] = [line.strip().split()[0] for line in match.group(2).splitlines() if line.strip() and not line.strip().startswith("//") and not line.strip().startswith("@@")]
    return models, enums


def parse_sql_tables(text):
    tables = {}
    pattern = re.compile(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:\w+\.)?[`\"]?(\w+)[`\"]?\s*\((.*?)\)\s*;", re.I | re.S)
    for match in pattern.finditer(text):
        name, body = match.groups()
        columns = set()
        for raw in body.splitlines():
            line = raw.strip().rstrip(",")
            if not line or re.match(r"(?i)(PRIMARY|FOREIGN|UNIQUE|CHECK|CONSTRAINT|KEY|INDEX)\b", line):
                continue
            column = re.match(r"[`\"]?(\w+)[`\"]?\s+", line)
            if column:
                columns.add(column.group(1))
        tables[name] = columns
    return tables


def inventory_prisma(findings):
    prisma_path = ROOT / "backend/prisma/schema.prisma"
    prisma_text = read_safe(prisma_path, findings)
    if prisma_text is None:
        return "# Prisma Models\n\nCHƯA RÕ: schema.prisma không đọc được trong giới hạn 200 KB.\n"
    models, enums = parse_prisma(prisma_text)
    lines = ["# Prisma Models", "", "## Models"]
    expected_tables = {}
    for name, model in models.items():
        fields = []
        expected_columns = set()
        for field_name, info in model["fields"].items():
            annotations = " ".join(info["markers"])
            relation = " [quan hệ]" if info["relation"] else ""
            fields.append(f"`{field_name}: {info['type']}`{relation}{' ' + annotations if annotations else ''}")
            if not info["relation"]:
                expected_columns.add(info["db_name"])
        expected_tables[model["table"]] = expected_columns
        lines.append(f"### {name} (bảng `{model['table']}`)")
        lines.append("- Fields: " + (", ".join(fields) or "không có"))
        lines.append("- Index/unique: " + ("; ".join(model["indexes"]) if model["indexes"] else ", ".join(f["field"] if isinstance(f, dict) else str(f) for f in [] ) or "không khai báo @@index/@@unique/@@id"))
    lines.extend(["", "## Enums"])
    if enums:
        for name, members in enums.items():
            lines.append(f"- `{name}`: {', '.join(members)}")
    else:
        lines.append("- Không có enum khai báo.")

    sql_path = ROOT / "database/schema.sql"
    sql_text = read_safe(sql_path, findings) if sql_path.exists() else None
    lines.extend(["", "## Khác biệt giữa schema.sql và schema.prisma"])
    if sql_text is None:
        lines.append("- CHƯA RÕ: không có schema.sql trong phạm vi hoặc file vượt 200 KB.")
        return "\n".join(lines) + "\n"
    sql_tables = parse_sql_tables(sql_text)
    prisma_names = {name.lower(): (name, columns) for name, columns in expected_tables.items()}
    sql_names = {name.lower(): (name, columns) for name, columns in sql_tables.items()}
    only_prisma = sorted(prisma_names.keys() - sql_names.keys())
    only_sql = sorted(sql_names.keys() - prisma_names.keys())
    lines.append("- Bảng chỉ có trong Prisma: " + (", ".join(prisma_names[key][0] for key in only_prisma) or "không thấy"))
    lines.append("- Bảng chỉ có trong SQL: " + (", ".join(sql_names[key][0] for key in only_sql) or "không thấy"))
    common = sorted(prisma_names.keys() & sql_names.keys())
    mismatches = []
    for key in common:
        prisma_cols = {column.lower() for column in prisma_names[key][1]}
        sql_cols = {column.lower() for column in sql_names[key][1]}
        missing_sql = sorted(prisma_cols - sql_cols)
        missing_prisma = sorted(sql_cols - prisma_cols)
        if missing_sql or missing_prisma:
            mismatches.append(f"{prisma_names[key][0]}: chỉ Prisma={','.join(missing_sql) or '-'}; chỉ SQL={','.join(missing_prisma) or '-'}")
    lines.append("- Cột khác biệt: " + ("; ".join(mismatches) if mismatches else "không thấy trong các bảng so khớp"))
    return "\n".join(lines) + "\n"


def inventory_legal(findings):
    root = ROOT / "legal"
    lines = ["# Legal Index", ""]
    for path in source_files(root, {".md"}):
        text = read_safe(path, findings)
        if text is None:
            lines.append(f"## {path.relative_to(root).as_posix()}\n- CHƯA RÕ: vượt 200 KB.")
            continue
        headings = [(match.group(1), match.group(2).strip()) for line in text.splitlines() if (match := re.match(r"^(#{1,2})\s+(.+?)\s*#*\s*$", line))]
        title = next((heading for level, heading in headings if level == "#"), "CHƯA RÕ")
        h2 = [heading for level, heading in headings if level == "##"]
        relative = path.relative_to(root).as_posix()
        lines.extend([f"## {relative}", f"- Tiêu đề: {title}", "- H2: " + ("; ".join(h2) if h2 else "không có"), ""])
    return "\n".join(lines).rstrip() + "\n"


def ts_test_names(text):
    pattern = re.compile(r"\b(?:describe|it|test)\s*\(\s*(['\"`])([^'\"`\r\n]*)\1")
    return [f"{match.group(0).split('(')[0].strip()} {match.group(2)}" for match in pattern.finditer(text)]


def python_test_names(text):
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return ["CHƯA RÕ: không phân tích được cú pháp Python"]
    names = []
    class Visitor(ast.NodeVisitor):
        def visit_FunctionDef(self, node):
            if node.name.startswith("test_"):
                names.append(node.name)
            self.generic_visit(node)

        visit_AsyncFunctionDef = visit_FunctionDef

        def visit_ClassDef(self, node):
            if node.name.startswith("Test"):
                names.append(node.name)
            self.generic_visit(node)
    Visitor().visit(tree)
    return names


def inventory_tests(findings, backend_status, python_status):
    lines = ["# Test Inventory", ""]
    groups = [
        ("backend", source_files(ROOT / "backend", {".ts"})),
        ("apps/web/src/tests", source_files(ROOT / "apps/web/src/tests", {".ts", ".tsx", ".js", ".jsx"})),
        ("tests", source_files(ROOT / "tests", {".py"})),
    ]
    for label, paths in groups:
        selected = [path for path in paths if path.name.endswith(".spec.ts")] if label == "backend" else paths
        lines.extend([f"## {label}", ""])
        for path in selected:
            text = read_safe(path, findings)
            relative = path.relative_to(ROOT).as_posix()
            if text is None:
                lines.append(f"- `{relative}`: CHƯA RÕ (vượt 200 KB)")
                continue
            names = python_test_names(text) if path.suffix == ".py" else ts_test_names(text)
            lines.append(f"- `{relative}`: " + ("; ".join(names) if names else "không thấy describe/it/test"))
        if not selected:
            lines.append("- Không thấy file test.")
        lines.append("")
    lines.extend(["## Kết quả chạy", f"- `npm test` trong backend: {backend_status}", f"- `make test` ở root: {python_status}"])
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in {"2", "3", "4", "5"}:
        raise SystemExit("Dùng: python tools/build_ai_inventories.py <2|3|4|5> [backend-status] [python-status]")
    step = sys.argv[1]
    findings = set()
    if step == "2":
        target, content = "BACKEND_INVENTORY.md", inventory_backend(findings)
    elif step == "3":
        target, content = "PRISMA_MODELS.md", inventory_prisma(findings)
    elif step == "4":
        target, content = "LEGAL_INDEX.md", inventory_legal(findings)
    else:
        backend_status = sys.argv[2] if len(sys.argv) > 2 else "CHƯA CHẠY: chưa truyền kết quả lệnh"
        python_status = sys.argv[3] if len(sys.argv) > 3 else "CHƯA CHẠY: chưa truyền kết quả lệnh"
        target, content = "TEST_INVENTORY.md", inventory_tests(findings, backend_status, python_status)
    write_new(PACK / target, content)
    flush_findings(findings)
    print(f"created=ai-pack/{target} secret_locations={len(findings)}")


if __name__ == "__main__":
    main()